### ISSUE TITLE
 rails g spree_i18n:install  fails rails4

### ISSUE THREAD

**Issue by danil-z** [spree-contrib/spree_i18n#275]
does spree_i18n require globalize3?
could you suggest working fork globalize3 gem with rails4...?

``` ruby
#Gemfile
gem 'spree', github: 'spree/spree'
gem "spree_auth_devise", :github => "spree/spree_auth_devise"
gem 'spree_i18n', github: 'spree/spree_i18n'
```

➜  my_store  rails g spree_i18n:install  

```
/Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require': cannot load such file -- globalize3 (LoadError)
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/spree_i18n-51b31be20081/lib/spree_i18n/engine.rb:1:in `<top (required)>'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/spree_i18n-51b31be20081/lib/spree_i18n.rb:3:in `<top (required)>'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /Users/user/code/my_store/config/application.rb:7:in `<top (required)>'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/railties-4.0.0/lib/rails/commands.rb:44:in `require'
    from /Users/user/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/railties-4.0.0/lib/rails/commands.rb:44:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by parseb** [comment]
I don't get any error it just freezes on me and the only way out is ctrl + z. I'm using Ubuntu. 
I get a "Could not find table 'spree_taxonomy_translations'" when I open the app probably because the migrations have not run yet. 

This is my gemfile: 
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'therubyracer'

gem 'spree', '3.0.0'

gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'

gem 'globalize', '~> 5.0.0'

gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-0-stable'


Spree is useless to me if I can't translate it in my native language. (been in this world for a day and, after many google searches and of course, deface, I feel like Spree has no future.)

**Comment by JDutil** [comment]
@parseb if you have `spring` bundled you may want to try commenting it out, and rebundle without it.  It's been known to cause random issues with installation.
