### ISSUE TITLE
friendly_id version contrain

### ISSUE THREAD

**Issue by Antronin** [spree-contrib/spree_i18n#506]
Hi,

I forked the repo to create a new translation file. Before I start translation I wnted to run the tests. However on a clean checkou I cannot run `bundle install` because it drops the following error message:
```
Bundler could not find compatible versions for gem "friendly_id":
  In Gemfile:
    spree (>= 0) ruby depends on
      friendly_id (~> 5.0.4) ruby

    spree_i18n (>= 0) ruby depends on
      friendly_id (5.1.0)
```
I don't see where this gem is referenced in spree_i18n, the gemspec file only states 
```
  s.add_runtime_dependency 'friendly_id-globalize'
```
Maybe this is what causes the problem, but I don't know how to resolve it. Any help is appreciated.
FYI: I checked out `2-4-stable` branch from spree_i18n.

**Comment by futhr** [comment]
Hi @Antronin, seems there was a version dependency change 5 days ago in `friendly_id-globalize` that mismatch what defined in spree core `.gemspec`, but there has not been any new release to RubyGems since August 2013 so it should not affect anything.

https://github.com/norman/friendly_id-globalize/blob/master/friendly_id-globalize.gemspec#L19
https://github.com/spree-contrib/spree_i18n/blob/2-4-stable/spree_i18n.gemspec#L20
https://github.com/spree/spree/blob/2-4-stable/core/spree_core.gemspec#L28

In this commit https://github.com/norman/friendly_id-globalize/commit/a5f7d9f970347e4a232057fc885cddbe28d0bd6a#diff-2e9b68eb694e4739c9a361369b7bcb82R19 `friendly_id-globalize` no longer allow versions of `friendly_id` lower then v5.1.0

Can you run `gem list | grep friendly_id` and paste output here please. Resent changes should be in `friendly_id-globalize` v1.0.0.alpha2.

**Comment by JDutil** [comment]
Run `bundle update` instead.
